@startuml HealthInsuranceERP - Component Diagram - Policy Management

scale 2/3

center header
    C4 Architecture: Health Insurance ERP System - Component Diagram (Policy Management)
endheader

title Health Insurance ERP System - Component Diagram (Policy Management)

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

ContainerDb(database, "Database", "SQL Database", "Transactional data store")

Container_Boundary(policymanagement, "Policy Management") {
    Component(domain, "Domain", "Entities and Domain Services", "netstandard2.1/net80")
    Component(contract, "Contract", "Application DTOs", "Class Library")
    Component(infrastructure, "Infrastructure", "Repository (Use Cases & Business Logic), Data Access, Caching Logic and Infrastructure Services", "Class Library")
    Component(application, "Application", "Application Logic", "Class Library")
    Component(presentation, "Presentation", "UI and External Interfaces", "ASP.NET Core API")

    Component(unitTests, "Unit Tests", "Tests all in-memory logic", "xUnit/NUnit")
    Component(integrationTests, "Integration Tests", "Tests all logic that flows between different memory spaces", "xUnit/NUnit")
}

Rel(infrastructure, application, "Project Reference")
Rel(application, contract, "Project Reference")
Rel(contract, domain, "Project Reference")
Rel(presentation, infrastructure, "Project Reference")
Rel(unitTests, infrastructure, "Project Reference")
Rel(integrationTests, infrastructure, "Project Reference")

Rel(infrastructure, database, "ConnectionString")

center footer

    Diagram Footer v1.0
    Designed by @ KyreeHenry
endfooter
@enduml
