@startuml HealthInsuranceERP - Component Diagram - Policy Management

scale 2/3

center header
    C4 Architecture: Health Insurance ERP System - Component Diagram (Policy Management)
endheader

title Health Insurance ERP System - Component Diagram (Policy Management)

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

ContainerDb(database, "Database", "SQL Database", "Transactional data store")

Container_Boundary(policymanagement, "Policy Management") {
    Component(domain, "Domain", "Entities, Business Logic, and Domain Services", "netstandard2.1/net80")
    Component(infrastructure, "Infrastructure", "Repository, Data Access, Caching Logic", "Entity Framework Core")
    Component(application, "Application", "Application Logic and Use Cases", "ASP.NET Core")
    Component(presentation, "Presentation", "UI and External Interfaces", "ASP.NET Core Blazor")

    Component(unitTests, "Unit Tests", "Tests all in-memory logic", "xUnit/NUnit")
    Component(integrationTests, "Integration Tests", "Tests all logic that flows between different memory spaces", "xUnit/NUnit")
}

Rel(infrastructure, domain, "Project Reference")
Rel(application, domain, "Project Reference")
Rel(presentation, application, "Project Reference")
Rel(unitTests, domain, "Project Reference")
Rel(unitTests, infrastructure, "Project Reference")
Rel(unitTests, application, "Project Reference")
Rel(integrationTests, domain, "Project Reference")
Rel(integrationTests, infrastructure, "Project Reference")
Rel(integrationTests, application, "Project Reference")

Rel(infrastructure, database, "ConnectionString")

center footer

    Diagram Footer v1.0
    Designed by @ KyreeHenry
endfooter
@enduml
